"""
SQLite / PostgreSQL 양쪽에서 같은 SQL을 쓰기 위한 얇은 계층.

**ORM을 쓰지 않는다.** 쿼리가 서른 개 남짓이고 전부 단순하다.
SQLAlchemy를 얹으면 의존성과 학습 비용이 쿼리보다 커진다.

두 방언의 차이는 넷뿐이다.

    플레이스홀더      ?                    ->  %s
    중복 무시 삽입    INSERT OR IGNORE     ->  ON CONFLICT DO NOTHING
    자동 증가         AUTOINCREMENT        ->  GENERATED BY DEFAULT AS IDENTITY
    세션 설정         PRAGMA               ->  없음

나머지는 그대로 통한다. 특히:

    ON CONFLICT(...) DO UPDATE SET    양쪽 문법이 같다
    substr(ts, 12, 2)                 양쪽에 있다. ISO 문자열에서 '시'를 뽑는다
                                      (strftime 은 SQLite 전용이라 쓰지 않는다)

시각을 TEXT(ISO)로 저장하는 것도 의도다. 문자열 비교가 곧 시간 비교라
BETWEEN 이 그대로 동작하고, 타임존 처리로 새는 구멍이 없다.

DATABASE_URL 이 있으면 PostgreSQL, 없으면 SQLite 파일을 쓴다.
"""

from __future__ import annotations

import os
import re
import sqlite3
from contextlib import contextmanager
from pathlib import Path
from typing import Any, Iterator

DEFAULT_SQLITE = Path(__file__).resolve().parent.parent / "petcare.db"


def database_url() -> str | None:
    """배포 환경이 주는 접속 문자열. 없으면 로컬 SQLite."""
    url = os.environ.get("DATABASE_URL", "").strip()
    if not url:
        return None
    # Render·Heroku 계열이 postgres:// 로 주는데 psycopg 는 postgresql:// 를 받는다
    if url.startswith("postgres://"):
        url = "postgresql://" + url[len("postgres://"):]
    return url


def is_postgres() -> bool:
    return database_url() is not None


def backend() -> str:
    return "postgresql" if is_postgres() else "sqlite"


# ---------------------------------------------------------------------------
# SQL 변환
# ---------------------------------------------------------------------------

_INSERT_IGNORE = re.compile(
    r"INSERT\s+OR\s+IGNORE\s+INTO", re.IGNORECASE
)


def translate(sql: str) -> str:
    """SQLite 문법으로 쓴 쿼리를 PostgreSQL 용으로 바꾼다."""
    if not is_postgres():
        return sql

    if _INSERT_IGNORE.search(sql):
        sql = _INSERT_IGNORE.sub("INSERT INTO", sql)
        # VALUES(...) 뒤에 붙인다. 이미 ON CONFLICT 가 있으면 건드리지 않는다.
        if "ON CONFLICT" not in sql.upper():
            sql = sql.rstrip().rstrip(";") + " ON CONFLICT DO NOTHING"

    return sql.replace("?", "%s")


def translate_ddl(ddl: str) -> str:
    """스키마 DDL 을 PostgreSQL 용으로 바꾼다."""
    if not is_postgres():
        return ddl

    out = ddl.replace(
        "INTEGER PRIMARY KEY AUTOINCREMENT",
        "INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
    )
    # PRAGMA 는 SQLite 전용. 줄 단위로 제거한다.
    out = "\n".join(
        line for line in out.splitlines()
        if not line.strip().upper().startswith("PRAGMA")
    )
    return out


# ---------------------------------------------------------------------------
# 커넥션 래퍼
# ---------------------------------------------------------------------------

class Conn:
    """
    execute / executemany 시그니처를 양쪽에서 동일하게 맞춘다.

    행 접근은 둘 다 `row["column"]` 으로 통일한다
    (sqlite3.Row 와 psycopg dict_row 가 같은 인터페이스를 준다).
    """

    def __init__(self, raw: Any, pg: bool) -> None:
        self._raw = raw
        self._pg = pg

    # -- 질의 ---------------------------------------------------------------

    def execute(self, sql: str, params: tuple | list = ()) -> Any:
        cur = self._raw.cursor()
        cur.execute(translate(sql), params)
        return cur

    def executemany(self, sql: str, seq: list) -> Any:
        cur = self._raw.cursor()
        if seq:
            cur.executemany(translate(sql), seq)
        return cur

    def executescript(self, ddl: str) -> None:
        ddl = translate_ddl(ddl)
        if self._pg:
            # psycopg 는 여러 문장을 한 번에 실행할 수 있다
            self._raw.cursor().execute(ddl)
        else:
            self._raw.executescript(ddl)

    # -- 트랜잭션 -----------------------------------------------------------

    def commit(self) -> None:
        self._raw.commit()

    def close(self) -> None:
        self._raw.close()


@contextmanager
def connect(path: Path | str | None = None) -> Iterator[Conn]:
    """
    DATABASE_URL 이 있으면 PostgreSQL, 없으면 SQLite.

    path 는 SQLite 일 때만 의미가 있다. 테스트가 임시 파일을 쓰기 위한 것이다.
    """
    url = database_url()

    if url:
        import psycopg
        from psycopg.rows import dict_row

        raw = psycopg.connect(url, row_factory=dict_row, autocommit=False)
        conn = Conn(raw, pg=True)
    else:
        raw = sqlite3.connect(str(path or DEFAULT_SQLITE))
        raw.row_factory = sqlite3.Row
        # 게이트웨이 여러 대가 동시에 올릴 수 있다
        raw.execute("PRAGMA journal_mode=WAL")
        raw.execute("PRAGMA foreign_keys=ON")
        conn = Conn(raw, pg=False)

    try:
        yield conn
        conn.commit()
    finally:
        conn.close()
